CREATE TABLE Alumno(
IdAlumno NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
Nombre VARCHAR(50) NOT NULL,
ApellidoPaterno VARCHAR(50),
ApellidoMaterno VARCHAR(50)
);

CREATE TABLE Materia (
IdMateria NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
Nombre VARCHAR(50) NOT NULL,
Costo NUMBER NOT NULL
);

CREATE TABLE Alumno_Materia (
IdAlumnoMateria NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
IdMateria NUMBER NOT NULL,
IdAlumno NUMBER NOT NULL,
FOREIGN KEY (IdMateria) REFERENCES Materia(IdMateria),
FOREIGN KEY (IdAlumno) REFERENCES Alumno(IdAlumno)
);