CREATE TABLE Editorial (
IdEditorial NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
Nombre VARCHAR(50) NOT NULL
);

CREATE TABLE Genero(
IdGenero NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
Nombre VARCHAR(50) NOT NULL
);

CREATE TABLE Autor (
IdAutor NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
Nombre VARCHAR(50) NOT NULL,
ApellidoPaterno VARCHAR(50) NOT NULL,
ApellidoMaterno VARCHAR(50),
Nacionalidad VARCHAR(50)
);

CREATE TABLE Estatus(
IdEstatus NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
Nombre VARCHAR(50)
);

CREATE TABLE Usuario (
IdUsuario NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
Nombre VARCHAR(50),
ApellidoPaterno VARCHAR(50) NOT NULL,
ApellidoMaterno VARCHAR(50),
Email VARCHAR(70),
Telefono VARCHAR(25),
Direccion VARCHAR(155),
FechaNacimiento DATE
);

CREATE TABLE LIBRO (
IdLibro NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
IdEditorial NUMBER,
FOREIGN KEY (IdEditorial) REFERENCES Editorial(IdEditorial),
IdGenero NUMBER,
FOREIGN KEY (IdGenero) REFERENCES Genero(IdGenero),
IdAutor NUMBER,
FOREIGN KEY (IdAutor) REFERENCES Autor(IdAutor),
Titulo VARCHAR(70) NOT NULL,
Descripcion CLOB,
NumeroPaginas NUMBER,
Stock NUMBER,
PrecioPorDia NUMBER,
PrecioDiaPenitencia NUMBER
);

CREATE TABLE Prestamo (
IdPrestamo NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
IdLibro NUMBER,
FOREIGN KEY (IdLibro) REFERENCES LIBRO(IdLibro),
IdUsuario NUMBER,
FOREIGN KEY (IdUsuario) REFERENCES Usuario(IdUsuario),
IdEstatus NUMBER,
FOREIGN KEY (IdEstatus) REFERENCES Estatus(IdEstatus),
FechaPrestamo DATE NOT NULL,
FechaDevolucionAsignada DATE NOT NULL,
FechaDevolucion DATE,
CostoTotal NUMBER
);

